rebuild project structure
C0623I1-project-module-6/best-ticket-front pull request #1
Opened 2023-12-26 17:50 UTC by baoandlk93

#add GuestLayout
#add "react-icons": "^4.12.0"
#move directory page to directory layouts
#define AdminHeader
#define Login component
#define Register component
#define Sidebar component
#define Navbar component

2023-12-26 17:52 UTC, nguyenthanhdat1997 approved these changes
good job!

2023-12-26 18:10 UTC, thinhphan1122 approved these changes
Approved.

2023-12-26 20:26 UTC, phaiphan approved these changes

2023-12-26 22:06 UTC, daonguyendev requested changes
Please update some codes according to the comments below

2023-12-26 22:06 UTC, daonguyendev commented on src/redux/api/UserApi.js
> +import {WEB_API} from "../../ultility/AppConstant.js"
Should rename WEB_API to BEST_TICKET_API

2023-12-27 01:13 UTC, baoandlk93 commented on src/component/Navbar.jsx
> +        localStorage.setItem("theme", theme)
Thank you for your comment, I will fix it in the next commit !

2023-12-27 02:11 UTC, NhanTran262 approved these changes
Well done

2023-12-27 02:13 UTC, baoandlk93 reviewed
Everything ok !

2023-12-27 02:15 UTC, phaiphan approved these changes

2023-12-27 02:16 UTC, nguyenthanhdat1997 reviewed
good job

2023-12-27 02:16 UTC, NhanTran262 approved these changes
Well done

2023-12-27 02:32 UTC, phaiphan approved these changes
good job

2023-12-27 02:34 UTC, thinhphan1122 approved these changes
Reviewed

2023-12-27 02:35 UTC, thinhphan1122 reviewed
Re-reviewed

2023-12-27 02:46 UTC, baoandlk93 reviewed
Reviews done

2023-12-27 02:48 UTC, thinhphan1122 approved these changes
Re-approve

2023-12-27 02:48 UTC, nguyenthanhdat1997 reviewed
nice

2023-12-27 02:49 UTC, NhanTran262 approved these changes
GLTM

2023-12-27 02:49 UTC, nguyenthanhdat1997 approved these changes
LGTM!

2023-12-27 02:57 UTC, nguyenthanhdat1997 reviewed
LGTM!

2023-12-27 02:58 UTC, thinhphan1122 approved these changes
Approved!

2023-12-27 02:58 UTC, NhanTran262 approved these changes
GLTM

2023-12-27 02:59 UTC, phaiphan approved these changes
good

2023-12-27 03:00 UTC, merged